class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'dl'
        self.UnzipMirrorCommand = 'unzip'
        self.TarMirrorCommand = 'tar'
        self.CancelMirror = 'can'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'cari'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'ulang'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help1'
        self.LogCommand = 'logs'
        self.SpeedCommand = 'speed'
        self.CloneCommand = 'c'
        self.CountCommand = 'count'
        self.WatchCommand = 'youtube'
        self.TarWatchCommand = 'taryt'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'sh'
        self.UpdateCommand = 'upbot'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
